MODEL:
  NAME: resnet50
LOSS:
  CLA_LOSS: crossentropylabelsmooth
  CAL: cal
DATA:
  DATASET: ltcc
  ROOT:
  TRAIN_BATCH: 16
  TEST_BATCH: 128
  NUM_INSTANCES: 4
  HEIGHT: 384
  WIDTH: 192
EVAL_MODE: False
OUTPUT:
TAG: base+unclo